<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NutAgent.Tray</RootNamespace>
    <AssemblyName>ups-tray</AssemblyName>
    <ApplicationIcon>Resources\icon_online.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\*.ico" />
  </ItemGroup>
</Project>
